# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_payment', '0002_paymentinfo_hash_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='message',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='status',
        ),
    ]
