# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20160218_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Terminal name')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Terminals',
                'permissions': (('terminal_view', 'Can view Terminal'), ('terminal_all_view', 'Can view ALL Terminal')),
                'verbose_name': 'Terminal',
            },
        ),
        migrations.AlterModelOptions(
            name='cargotype',
            options={'permissions': (('cargotype_view', 'Can view CargoType'), ('cargotype_all_view', 'Can view ALL CargoTypes')), 'verbose_name': 'Cargo Type', 'verbose_name_plural': 'Cargo Types'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'permissions': (('direction_view', 'Can view Direction'), ('direction_all_view', 'Can view ALL Direction')), 'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.AlterModelOptions(
            name='passengertransporttype',
            options={'permissions': (('passengertransporttype_view', 'Can view PassengerTransportType'), ('passengertransporttype_all_view', 'Can view ALL PassengerTransportTypes')), 'verbose_name': 'Passenger Transport Type', 'verbose_name_plural': 'Passenger Transport Types'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'permissions': (('port_view', 'Can view Port'), ('port_all_view', 'Can view ALL Port')), 'verbose_name': 'Port', 'verbose_name_plural': 'Ports'},
        ),
        migrations.AlterModelOptions(
            name='vessel',
            options={'permissions': (('vessel_view', 'Can view Vessel'), ('vessel_all_view', 'Can view ALL Vessels')), 'verbose_name': 'Vessel', 'verbose_name_plural': 'Vessels'},
        ),
        migrations.AlterModelOptions(
            name='vesselcargofee',
            options={'permissions': (('vesselcargofee_view', 'Can view VesselCargoFee'), ('vesselcargofee_all_view', 'Can view ALL VesselCargoFees')), 'verbose_name': 'Vessel Cargo Fee', 'verbose_name_plural': 'Vessel Cargo Fees'},
        ),
        migrations.AlterModelOptions(
            name='vesselsshedule',
            options={'permissions': (('vesselshedule_view', 'Can view VesselsShedule'), ('vesselshedule_all_view', 'Can view ALL VesselsShedules')), 'verbose_name': 'PortsShedule', 'verbose_name_plural': 'PortsShedules'},
        ),
        migrations.AlterField(
            model_name='direction',
            name='from_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_d', to='booking.Terminal', verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='booking.Terminal', verbose_name='To'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Port', verbose_name='Port'),
        ),
    ]
