# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20160218_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='description_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='name_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Terminal name'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Terminal name'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Terminal name'),
        ),
    ]
