# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 08:53
from __future__ import unicode_literals

import booking.utils.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20160219_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vesselsshedule',
            options={'permissions': (('vesselshedule_view', 'Can view VesselsShedule'), ('vesselshedule_all_view', 'Can view ALL VesselsShedules')), 'verbose_name': 'Vessels Shedule', 'verbose_name_plural': 'Vessels Shedules'},
        ),
        migrations.AlterField(
            model_name='vesselsshedule',
            name='shedule_id',
            field=models.CharField(default=booking.utils.tools.rand_vessel_shedule, max_length=25, unique=True, verbose_name='Shedule ID'),
        ),
    ]
