# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20160220_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='owner',
        ),
        migrations.AlterField(
            model_name='bookinginformation',
            name='vessel_shedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.VesselsShedule', verbose_name='Voyage'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
