# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20160222_0703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactionAgentBalance',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='is_pay',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='price',
        ),
    ]
