# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20160224_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('paid_price', models.FloatField(verbose_name='Paid price')),
                ('is_pay', models.BooleanField(verbose_name='Is Pay')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingInformation', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'permissions': (('transaction_view', 'Can view Transaction'), ('transaction_all_view', 'Can view ALL Transactions'), ('transaction_object_owner', 'Can own Transaction')),
            },
        ),
        migrations.AlterModelOptions(
            name='transactionagentbalance',
            options={'permissions': (('transactionagentbalance_view', 'Can view Transaction Agent Balance'), ('transactionagentbalance_all_view', 'Can view ALL Transactions Agent Balance'), ('transactionagentbalance_object_owner', 'Can own Transaction Agent Balance')), 'verbose_name': 'Transaction agent', 'verbose_name_plural': 'Transactions agent'},
        ),
    ]
