# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20160224_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginformation',
            name='cargo_count',
            field=models.IntegerField(default=0, verbose_name='Cargo count'),
        ),
        migrations.AddField(
            model_name='bookinginformation',
            name='passenger_count',
            field=models.IntegerField(default=0, verbose_name='Passenger count'),
        ),
    ]
