# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 08:51
from __future__ import unicode_literals

import booking.utils.tools
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20160224_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField(verbose_name='Arrival date')),
                ('departure_date', models.DateTimeField(verbose_name='Departure date')),
                ('schedule_id', models.CharField(default=booking.utils.tools.rand_vessel_shedule, max_length=25, unique=True, verbose_name='Schedule ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Direction', verbose_name='Direction')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Vessel', verbose_name='Vessel')),
            ],
            options={
                'verbose_name': 'Vessels Schedule',
                'permissions': (('vesselschedule_view', 'Can view Vessels Schedule'), ('vesselschedule_all_view', 'Can view ALL Vessels Schedules')),
                'verbose_name_plural': 'Vessels Schedules',
            },
        ),
        migrations.RemoveField(
            model_name='vesselsshedule',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='vesselsshedule',
            name='vessel',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='vessel_shedule',
        ),
        migrations.AddField(
            model_name='bookingcargoitem',
            name='cargo_ticket_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bookingpassengeritem',
            name='passenger_ticket_id',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VesselsShedule',
        ),
        migrations.AddField(
            model_name='bookinginformation',
            name='vessel_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.VesselsSchedule', verbose_name='Voyage'),
            preserve_default=False,
        ),
    ]
