# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20160225_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpassengeritem',
            name='passenger_ticket_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
