# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20160226_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcargoitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargoes', to='booking.BookingInformation', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='bookingpassengeritem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='booking.BookingInformation', verbose_name='Booking'),
        ),
    ]
