# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20160226_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingcargoitem',
            old_name='cargo_ticket_id',
            new_name='ticket_id',
        ),
        migrations.RenameField(
            model_name='bookingpassengeritem',
            old_name='passenger_ticket_id',
            new_name='ticket_id',
        ),
    ]
