# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20160226_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vesselsschedule',
            options={'ordering': ['-created_at'], 'permissions': (('vesselschedule_view', 'Can view Vessels Schedule'), ('vesselschedule_all_view', 'Can view ALL Vessels Schedules')), 'verbose_name': 'Vessels Schedule', 'verbose_name_plural': 'Vessels Schedules'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingInformation', verbose_name='Booking'),
        ),
    ]
