# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20160229_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargotype',
            name='name_az',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cargotype',
            name='name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='cargotype',
            name='name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='passengertransporttype',
            name='description_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengertransporttype',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengertransporttype',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengertransporttype',
            name='name_az',
            field=models.CharField(max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='passengertransporttype',
            name='name_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='passengertransporttype',
            name='name_ru',
            field=models.CharField(max_length=25, null=True, verbose_name='Name'),
        ),
    ]
