# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20160229_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginformation',
            name='contact_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bookinginformation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bookingcargoitem',
            name='mark',
            field=models.CharField(max_length=25, verbose_name='Mark/Model'),
        ),
    ]
