# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20160229_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginformation',
            name='booking_date',
        ),
    ]
