# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_bookinginformation_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginformation',
            name='owner',
        ),
    ]
