# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_booking_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginformation',
            name='type',
            field=models.CharField(choices=[('1', 'Away'), ('2', 'Return')], default='1', max_length=25),
            preserve_default=False,
        ),
    ]
