# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_bookinginformation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
    ]
