# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20160303_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginformation',
            name='cargo_count',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='contact_mail',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='bookinginformation',
            name='passenger_count',
        ),
    ]
