# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_auto_20160304_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cargo_count',
            field=models.IntegerField(default=0, verbose_name='Cargo count'),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_count',
            field=models.IntegerField(default=0, verbose_name='Passenger count'),
        ),
    ]
