# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_auto_20160304_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('1', 'One way'), ('2', 'Round trip')], max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transit_type',
            field=models.CharField(choices=[('1', 'Transit'), ('2', 'Non Transit')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transactionagentbalance',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
    ]
