# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_auto_20160304_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselpassengercapacity',
            name='passenger_transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_types', to='booking.PassengerTransportType', verbose_name='Passenger transport type'),
        ),
        migrations.AlterField(
            model_name='vesselpassengercapacity',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='booking.Vessel', verbose_name='Vessel'),
        ),
    ]
