# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_auto_20160305_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfee',
            name='transit_price',
            field=models.FloatField(default=1, verbose_name='Transit price'),
            preserve_default=False,
        ),
    ]
