# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_auto_20160305_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginformation',
            name='vessel_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_infos', to='booking.VesselsSchedule', verbose_name='Voyage'),
        ),
    ]
