# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_auto_20160306_1457'),
        ('booking', '0037_portfee_transit_price'),
    ]

    operations = [
    ]
