# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paid_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='booking.BookingInformation', verbose_name='Booking'),
        ),
    ]
