# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cargo_fee',
            field=models.FloatField(default=0, verbose_name='Cargo fee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='passenger_fee',
            field=models.FloatField(default=0, verbose_name='Passenger fee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transit_fee',
            field=models.FloatField(default=0, verbose_name='Transit fee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transit_percent',
            field=models.FloatField(default=0, verbose_name='Transit percent'),
        ),
    ]
