# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_transaction_port_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_price',
            field=models.FloatField(default=0, verbose_name='Paid price'),
        ),
    ]
