# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_auto_20160309_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='Is Pay'),
        ),
    ]
