# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_auto_20160309_1100'),
        ('booking', '0039_auto_20160308_0800'),
    ]

    operations = [
    ]
