# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-id'], 'permissions': (('bookingcheckin_view', 'Can check in Booking'),)},
        ),
    ]
