# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_auto_20160310_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-id'], 'permissions': (('bookingcheckin_view', 'Can check in Booking'), ('booking_view', 'Can view Booking'), ('booking_all_view', 'Can view ALL Bookings'))},
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='port_fee',
            field=models.FloatField(default=0, verbose_name='Port fee'),
        ),
    ]
