# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_auto_20160312_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/booking_ticket/'),
        ),
    ]
