# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
