# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160224_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='passport',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Passport'),
        ),
    ]
