# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_passport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'permissions': (('agent_view', 'Can view Agent'), ('agent_all_view', 'Can view ALL Agent'), ('agent_object_owner', 'Can own Agent')), 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
    ]
