# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160304_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('user_view', 'Can view Agent'), ('user_all_view', 'Can view ALL Agent'))},
        ),
    ]
